name: build-image

on:
  workflow_dispatch:
  push:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Build the docker image and push
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 --tag ${{ secrets.DOCKERHUB_USERNAME }}/hookscan:latest --file Dockerfile --push .
